### ISSUE TITLE
To-Do list from code review

### ISSUE THREAD

**Issue by calvinxp** [AGHSEagleRobotics/frc1388-2024#36]
### General
- [x] remove all unused imports
- [x] re-add `ShooterSubsystem` and `TransitionSubsystem` in `RobotContainer.java`
- [x] update the [2024 Robot Controls](https://docs.google.com/spreadsheets/d/1Rd3skivB0v4Bx_V3Fk02204wJFP0JmXSo-qAtKTbU1E/edit#gid=0) spreadsheet, they update the button bindings in `RobotContainer.java` to match
### Drive train related
- [x] figure out what action will set drive motors and other necessary motors to neutral mode, implement this
- [x] in `Robot.java`, change `m_robotContainer.m_driveTrain.setAllEncoderOffsets()` to `m_robotContainer.setAllEncoderOffsets()`, where `setAllEncoderOffsets()` is a method in robot container that calls `m_driveTrain.setAllEncoderOffsets()`
- [x] review speed scaling in `setDriveSpeed()` method in `SwerveModule.java` Maybe this code should be in `DriveTrain.java` Figure out where this math should be done, implement changes, then make sure auto PIDs still work
- [x] consider passing in controller in to commands, in stead of passing in individual buttons and axis
- [x] add documentation in `DriveCommand.java`
- [x] document the this method needs documentation method in `DriveCommand`

**Comment by calvinxp** [comment]
Item 4 finally done, issue marked as complete.
